version: '3'

volumes:
  data:

services:
  mongo:
    image: mongo:4
    restart: always
    volumes:
      - data:/data/db
    ports:
      - "9117:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=master
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=sisu
  api:
    build:
      context: ./sisu-server
    links:
      - mongo
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://master:${MONGO_PASSWORD}mongo:27017/sisu
      - JWT_SECRET=${JWT_SECRET}
  app:
    build:
      context: ./sisu-app
    ports:
      - 3000:80
    depends_on:
      - api